#!/bin/bash
dir=$1
for i in "$dir"/*
do 
if [[ -d "$i" ]]
then
if [[ "$i" == *"( ("* ]]
then 
mv "$i" "${i//( (/(}"
i="${i//( (/(}"
fi
if [[ "$i" == *"[080p]"* ]]
then 
mv "$i" "${i//\[080p\]/\[1080p\]}"
i="${i//\[080p\]/\[1080p\]}"

fi 
if [[ "$i" == *"."* ]]
then
parent_dir=$(dirname "$i")
        base_name=$(basename "$i")
        
        # Only replace dots in the actual folder name, not the path
        new_base="${base_name//./ }"
mv "$i" "$parent_dir/$new_base"
fi
else 
continue
fi
done
